version: '3.8'
networks:
  jedi:

services:
  app:
    image: app
    container_name: taskmanager
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - jedi

  db:
    container_name: taskmanager-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager
      POSTGRES_DB: taskmanager
    networks:
      - jedi